# Generated by Django 6.0.6 on 2026-06-03 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='tipos_plantas/')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de planta',
                'verbose_name_plural': 'Tipos de plantas',
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('cuidados', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(upload_to='plantas/')),
                ('estado', models.BooleanField(default=True)),
                ('tipo_planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantas', to='core.tipoplanta')),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
            },
        ),
    ]
